name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-and-push-image:
    uses: revisium/revisium-actions/.github/workflows/docker-build.yml@174e7053ee6cc463f376441c77e19dcb85919d41 # v0.3.6
    with:
      image_name: ${{ github.event.repository.name }}
      context: .
      dockerfile: Dockerfile
      emit_latest_tag: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
